# Numpy practice session 

In [ ]:
# pip install numpy 

In [3]:
# import this library in jupyter notebook 
import numpy as np 

# Creating an array using numpy 

In [5]:
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [8]:
type(price)


numpy.ndarray

In [9]:
type(food)

numpy.ndarray

In [10]:
len(food)

3

In [11]:
price[0:]

array([5, 5, 5])

In [12]:
food[1]

'Samosa'

In [13]:
price.mean()

5.0

In [14]:
# zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# ones 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
# specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# table 5
np.arange(5,55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
#line space 
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [29]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions 

In [32]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [33]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [35]:
b= np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [36]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [37]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D arrays

In [49]:
x = np.array([[1,2], [5,4]])
x

array([[1, 2],
       [5, 4]])

In [53]:
y = np.array([[6,7],[7,8]])
y

array([[6, 7],
       [7, 8]])

In [54]:
np.concatenate((x,y), axis=0)


array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [56]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [ ]:
a = np.array